### Upload User with Image
POST http://localhost:5001/employee HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FirstName"

Khalil
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="LastName"

Ahmad
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Designation"

Lecturer
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Email"

khalil@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CMS_id"

12-34
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="EmployeeId"

here is employeeid
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="OfficeExtension"

It is there
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="OfficeAddress"

Here is Address
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Type"

PERMANANT
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Phd"

true
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Skills"

app development,web development
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CurrentStatus"

Available
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Biography"

Here is my biography
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Message"

Here is my Message
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="BPS"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="BPS"

fariha.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
